services:
  redis:
    image: redis:7.4.2-bookworm
    container_name: redis-server
    ports:
      - "6379:6379"
    command: >
      sh -c "redis-server && sleep 7 && redis-cli"

  shop-application:
    build:
      context: ./shop-application
    container_name: shop-app
    depends_on:
      - redis
      - keycloak
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    depends_on:
      - redis
      - keycloak
    ports:
      - "8082:8082"

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - "8081:8080"
    command:
      - start-dev