spring:
  application:
    name: shop-app-yandex-practicum-sprint-5
  r2dbc:
    url: r2dbc:h2:mem:///shop
    username: h2
    password: h2
  thymeleaf:
    encoding: UTF-8
    mode: HTML
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  cache:
    type: redis

values:
  img_folder: F:\Images