spring:
  application:
    name: shop-app-yandex-practicum-sprint-5
  r2dbc:
    url: r2dbc:h2:mem:///shop
    username: h2
    password: h2
  thymeleaf:
    encoding: UTF-8
    mode: HTML
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  cache:
    type: redis
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/master
        registration:
          shop-client:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: shop-client
            client-secret: NioFeR8rMpO8nOU2cCdsfB1CGeBrygMl
            scope: profile
            clientAuthenticationMethod: client_secret_post

values:
  img_folder: F:\Images