spring:
  application:
    name: shop-app-yandex-practicum-sprint-5
  r2dbc:
    url: r2dbc:h2:mem:///shop
    username: h2
    password: h2
  thymeleaf:
    encoding: UTF-8
    mode: HTML

values:
  img_folder: F:\Images