spring:
  application:
    name: shop-app-yandex-practicum-sprint-5
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:shop
    username: h2
    password: h2

  jpa:
    hibernate:
      ddl-auto: update

values:
  img_folder: F:\Images