server:
  port: 8082

spring:
  jackson:
    date-format: org.openapitools.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/master